### ISSUE TITLE
MAC Address Column

### ISSUE THREAD

**Issue by Koshaani** [gorkemhacioglu/Knocker#1]
Hello Dear Sir and hope u are Healthy
My Name is Ahmad Reza Koshaani, and I wanna use your Port Knocker Project and would like to add MAC address column to the table that shows IPs and Ports.
Please if possible add this feature and if it is not plz guide me to how to do it.
thank you 
Best Regards: Koshaani

**Comment by gorkemhacioglu** [comment]
Thanks for your request.

Done! https://github.com/gorkemhacioglu/Knocker/releases/download/2023.1.8/Knocker.zip

**Comment by Koshaani** [comment]
Thank you for your early reply and I am honored by your cooperation.

**Comment by Koshaani** [comment]
Thanks for your cooperation, I wanted to use your nice program to evaluate the network on specific nodes that have specific ports open.
I am using an unusual port and it does not show me the physical address (MAC Address) of that port.
any guidance or change that is needed?
And I will be happy if you give me a way of communication so that I can be in touch with you.
Email or WhatsApp number.
Sincerely: Koshaani
Thank you again for all your cooperation
